import { 
  Circle, 
  Menu, 
  ArrowRight, 
  Instagram, 
  Youtube, 
  Mail, 
  Phone, 
  MapPin, 
  Star, 
  Play, 
  ExternalLink,
  Copy,
  Share,
  Settings,
  Crown,
  LogOut,
  User,
  MoreVertical,
  X
} from "lucide-react";

export const Icons = {
  logo: Circle,
  menu: Menu,
  arrowRight: ArrowRight,
  instagram: Instagram,
  youtube: Youtube,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  star: Star,
  play: Play,
  externalLink: ExternalLink,
  copy: Copy,
  share: Share,
  settings: Settings,
  crown: Crown,
  logOut: LogOut,
  user: User,
  moreVertical: MoreVertical,
  x: X,
}; 